### ISSUE TITLE
Update lifecycle method names to support React 16.3+ Async Rendering Changes

### ISSUE THREAD

**Issue by jrsinclair** [planttheidea/react-pure-lifecycle#4]
The React team have [announced that they will be deprecating a bunch of lifecycle methods soon](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html). If I'm [reading the code right](https://github.com/planttheidea/react-pure-lifecycle/blob/7186458a6738e10d267e15084c426fe38460437c/src/utils.js#L109), `react-pure-lifecycle` should mostly 'just work' if the new aliases (and new lifecycle method) are [added to the constants file](https://github.com/planttheidea/react-pure-lifecycle/blob/7186458a6738e10d267e15084c426fe38460437c/src/constants.js#L23).

**Comment by planttheidea** [comment]
Indeed! If you want to create a PR for this that'd be awesome, otherwise I'll be sure to tackle it in the next few weeks when I have some time.

**Comment by jrsinclair** [comment]
Working on a PR.

**Comment by planttheidea** [comment]
Fixed with release of `2.2.0`
